//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ipm.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.CashTransactions = new HashSet<CashTransaction>();
            this.AssetTransactions = new HashSet<AssetTransaction>();
            this.Assets = new HashSet<AssetInstance>();
        }
    
        public int AccountId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Currency { get; set; }
    
        public virtual Portfolio Portfolio { get; set; }
        public virtual ICollection<CashTransaction> CashTransactions { get; set; }
        public virtual ICollection<AssetTransaction> AssetTransactions { get; set; }
        public virtual ICollection<AssetInstance> Assets { get; set; }
        public virtual AccountBalanceBook BalanceBook { get; set; }
    }
}
