//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ipm.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTransaction
    {
        public AssetTransaction()
        {
            this.IsImported = false;
        }
    
        public int AssetTransactionId { get; set; }
        public TransactionType TransactionType { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public string TickerSymbol { get; set; }
        public string AssetName { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public decimal Price { get; set; }
        public decimal Quantity { get; set; }
        public decimal Commission { get; set; }
        public decimal Amount { get; set; }
        public bool IsImported { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AssetInstance AssetInstance { get; set; }
        public virtual CashTransaction CashTransaction { get; set; }
    }
}
