//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ipm.DataModel
{
    using System;
    
    public partial class BalanceBase
    {
        public decimal CashBalance { get; set; }
        public System.DateTime BalanceDate { get; set; }
        public decimal AssetsBookCost { get; set; }
        public decimal AssetsMarketCost { get; set; }
        public decimal Yield { get; set; }
        public decimal YieldPercent { get; set; }
        public decimal Return { get; set; }
        public decimal ReturnPercent { get; set; }
    }
}
