//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ipm.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashTransaction
    {
        public CashTransaction()
        {
            this.IsImported = false;
        }
    
        public int CashTransactionId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public decimal Amount { get; set; }
        public bool IsImported { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AssetTransaction AssetTransaction { get; set; }
    }
}
