//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ipm.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortfolioBalanceBook
    {
        public PortfolioBalanceBook()
        {
            this.BalanceBase = new BalanceBase();
        }
    
        public int Id { get; set; }
    
        public BalanceBase BalanceBase { get; set; }
    
        public virtual Portfolio Portfolio { get; set; }
    }
}
