//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ipm.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio
    {
        public Portfolio()
        {
            this.Accounts = new HashSet<Account>();
            this.BalanceBooks = new HashSet<PortfolioBalanceBook>();
        }
    
        public int PortfolioId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<PortfolioBalanceBook> BalanceBooks { get; set; }
    }
}
